#  the # is a comment
#
#  the sytax of a statement is
#  target: dependencies
#  [tab] system command

# Teddy Stephenson
# My Makefile Tutorial

all: myassingment


myassingment: house.o main.o
	g++ -o myassingment house.o main.o 

house.o: house.h
	g++ -c house.cpp

main.o: house.h
	g++ -c main.cpp

















